language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

install: true

script:
  - ./gradlew clean check jacocoTestReport coveralls --scan --stacktrace --parallel

after_success:
  - .buildscript/publishDocs.sh

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle

env:
  global:
    - secure: JsJTTZ1ZezjedDLB/9jtAgqj6ruGj/o/WFPTYxgv46VvbahSZYM2o16w9yYAHPwFNKhMIQXg9HoF7FfleQ4Jqz7ZPo1jpeOkU3bQO3YVYEyrLahd2K2gA6ipU8w9dEDDMBk21pvkbt0wke1FFIBmG71FHSOlYS7X4jETuy44Nd4=
