language: java

jdk:
 - oraclejdk7
 - oraclejdk8

script:
  - ./gradlew clean assemble check --stacktrace

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
