language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
  allow_failures:
    - os: osx

install: true

script:
  - ./gradlew clean test pmdMain findbugsMain checkstyleMain jacocoTestReport coveralls -Dreceipt --stacktrace

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
