language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

install: true

script:
  - ./gradlew clean test jacocoTestReport coveralls -Dscan --configure-on-demand --daemon --parallel --stacktrace

notifications:
  email: false

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle
