language: java

jdk:
  - oraclejdk8
  - oraclejdk9

matrix:
  allow_failures:
    - jdk: oraclejdk9

# prevent 'gradlew assemble'
install: true

script:
  - ./gradlew clean test jacocoTestReport coveralls --stacktrace

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
