language: java

jdk:
  - oraclejdk8

install: true

script:
  - ./gradlew clean test pmdMain findbugsMain checkstyleMain jacocoTestReport coveralls -Dreceipt --stacktrace

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
