language: java

jdk:
 - oraclejdk8

script:
  - ./gradlew clean assemble test jacocoTestReport coveralls --stacktrace

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
