install:
  - set JAVA_HOME=C:\Program Files\Java\jdk1.8.0

build_script:
  - gradlew.bat clean test pmdMain findbugsMain checkstyleMain jacocoTestReport coveralls -Dscan --configure-on-demand --daemon --parallel --stacktrace

artifacts:
  - path: build\reports\

cache:
  - "%USERPROFILE%\\.gradle"
  - "%USERPROFILE%\\.gradle\\caches\\"
  - "%USERPROFILE%\\.gradle\\wrapper\\"
